qp2 - use s3 aware reader
AdamaJava/adamajava pull request #290
Opened 2021-12-20 04:47 UTC by holmeso

# Description

Qprofiler2 needs to be able to access data on s3 (aws).
This PR updates qp2 to use the s3 aware seekable stream implementation that already exists in adamajava.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Changes have been tested on an ec2 instance, accessing a BAM on s3.
Changes have also been tested running on local HPC.

# Are WDL Updates Required?

No wdl updates are required.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes

2021-12-21 03:16 UTC, ChristinaXu2017 reviewed
the else statement is not required, the program must reach this area if no exception happen.

2021-12-24 00:42 UTC, ChristinaXu2017 requested changes

2021-12-24 00:43 UTC, holmeso commented on qprofiler2/src/org/qcmg/qprofiler2/QProfiler2.java
> -			} else {
The else statement has been removed

2021-12-24 00:51 UTC, ChristinaXu2017 approved these changes
all good

2021-12-24 00:52 UTC, merged